version: '3.7'

services:
  decidim:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis-queue
      - redis-cache
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    command: bundle exec rails server -b 0.0.0.0

  postgres:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  redis-queue:
    image: redis:6.0.12-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.0.12-alpine
    ports:
      - 6380:6379
    volumes:
      - redis-cache-data:/data

volumes:
  redis-queue-data:
  redis-cache-data:
  postgres-data:
